# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-01 07:00
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='不超过 255 个字符', max_length=255, verbose_name='名称')),
                ('width', models.IntegerField(default=1, help_text='占用的栏数, 取值1-4', verbose_name='宽度')),
                ('origin_image', models.CharField(help_text='不超过 255 个字符', max_length=255, verbose_name='原图的七牛key')),
                ('large_image', models.CharField(help_text='不超过 255 个字符', max_length=255, verbose_name='1920x的七牛key')),
                ('small_image', models.CharField(help_text='不超过 255 个字符', max_length=255, verbose_name='512x的七牛key')),
                ('date_upload', models.DateTimeField(help_text=' ', verbose_name='上传日期')),
                ('uploader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='上传者')),
            ],
        ),
    ]
