# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-06 03:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('attachment', models.FileField(upload_to='gallery/attachment/%Y/%m/%d')),
            ],
            options={
                'ordering': ['-created'],
                'verbose_name_plural': 'Galleries',
                'verbose_name': 'Detail Gallery',
            },
        ),
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('ip', models.CharField(max_length=40)),
            ],
            options={
                'ordering': ['-created'],
                'verbose_name_plural': 'Visitors',
                'verbose_name': 'Detail Visitor',
            },
        ),
        migrations.AlterField(
            model_name='post',
            name='cover',
            field=models.ImageField(blank=True, help_text='Optional cover post', null=True, upload_to='gallery/covers/%Y/%m/%d'),
        ),
        migrations.AddField(
            model_name='visitor',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_visitor', to='blog.Post'),
        ),
    ]
